### ISSUE TITLE
Request to add terms to CMO

### ISSUE THREAD

**Issue by Astghik-S** [rat-genome-database/CMO-Clinical-Measurement-Ontology#14]
Dear CMO Maintainers,

As part of the OBO Foundry principles, we aim to ensure that terms are included in the most appropriate ontology and avoid duplication across ontologies wherever possible. We are working on a biomarker ontology  (BMONT) and have identified several terms related to clinical and diagnostic metrics that may align well with the scope of CMO. Before proceeding to define these terms in our ontology, I wanted to reach out to ask if you would like to integrate any or all of the following terms into CMO.

The terms are as follows:

- cerebral blood volume

- gray matter volume

- N-Terminal Pro-B-Type Natriuretic Peptide

- blood lipid level

These terms are frequently used in clinical and biomedical research, especially in evaluating the performance of diagnostic tests and developing predictive models. We believe they could add value to CMO if they are not already included.

Please let us know if you would like to incorporate any of these terms, or if you would prefer that we proceed with defining them in our own ontology. We are happy to collaborate and ensure these terms are defined in a way that aligns with OBO Foundry standards.

Thank you for considering our request. We look forward to hearing your thoughts and are open to any guidance you may have.

Best regards,
Astghik Sargsyan
Fraunhofer Institute for Algorithms and Scientific Computing SCAI

**Comment by slaulederkind** [comment]
All of the suggested terms fit into the scope of CMO.  We add terms on an "as needed" basis.  Go ahead with your proposed terms and consider the definitions and children terms of:
cerebral blood flow rate (CMO:0003815)
brain morphological measurement (CMO:0000136)
blood NH2-terminal pro-B-type natriuretic peptide level (CMO:0002876)
blood lipid measurement (CMO:0000050)

**Comment by Astghik-S** [comment]
Thank you and sorry for the lat reply. 

We can reuse "blood NH2-terminal pro-B-type natriuretic peptide level (CMO:0002876)" for "N-Terminal Pro-B-Type Natriuretic Peptide".

I think you would agree that the following terms are not the same:

-  "cerebral blood volume" vs "cerebral blood flow rate (CMO:0003815)",
- "gray matter volume" vs "brain morphological measurement (CMO:0000136)",
- "blood lipid level" vs "blood lipid measurement (CMO:0000050).

**Comment by slaulederkind** [comment]
I agree with your assessment of "cerebral blood volume" vs "cerebral blood flow rate (CMO:0003815)" and "gray matter volume" vs "brain morphological measurement (CMO:0000136)".  However, "blood lipid level" and "blood lipid measurement (CMO:0000050) are really the same.  The issue is granularity, because blood lipid measurements are made by type (cholesterol, triglyceride, etc.).  "blood lipid level" or "blood lipid measurement” would be a parent term of a specific type of lipid measurement.



Stan Laulederkind, Ph.D.
Rat Genome Database
Department of Physiology
Medical College of Wisconsin
1000 N. 92nd St.
Milwaukee, WI 53226
Phone: 414-955-7513

**Comment by Astghik-S** [comment]
It is still not clear if you are adding the terms to the CMO ontology.

**Comment by slaulederkind** [comment]
We add terms to CMO upon request when they are needed for curation.  We do that for anyone using CMO for data curation.  Since you are developing an ontology in which some terms are similar to CMO terms, I suggest you create your own terms and use CMO terms as XREFs when appropriate.

**Comment by Astghik-S** [comment]
Alright, thank you!
