### ISSUE TITLE
NTR: relative maximal oxygen consumption

### ISSUE THREAD

**Issue by laurenechan** [rat-genome-database/CMO-Clinical-Measurement-Ontology#4]
Hello, I have a use case that is interested in a new CMO term:

term: 'relative maximal oxygen consumption'
parent: 'maximal oxygen consumption' (CMO:0000135)
definition: Maximum capacity of an individual's body to transport and utilize oxygen, usually measured during exercise as volume of oxygen per unit of time, relative to an individual's body weight.
synonyms: relative VO2 peak, relative VO2 max

**Comment by shurjenw** [comment]
Hi Lauren,
Could you send us the PMID where you found this term is needed.  Or you can request the CMO term directly from this link: https://sourceforge.net/p/rgddiseasevocabulary/rgdpmtickets/ and our curator Laulederkind, Stanley <slaulede@mcw.edu> will create the term and get back to you with term ID and availability.
Thanks,
Shur-Jen Wang
Rat Genome Database
